# Generated by Django 2.1.15 on 2022-02-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProdlineHistoryAllTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50, null=True)),
                ('line', models.CharField(max_length=50, null=True)),
                ('site', models.CharField(max_length=50, null=True)),
                ('due_date', models.CharField(max_length=50, null=True)),
                ('item_number', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=50, null=True)),
                ('to_complete', models.CharField(max_length=50, null=True)),
                ('receiving', models.BooleanField(blank='true', default=None, null=True)),
                ('allOkReceiving', models.BooleanField(blank='true', default=None, null=True)),
                ('comentarioReceiving', models.CharField(max_length=350, null=True)),
                ('shipping', models.BooleanField(blank='true', default=None, null=True)),
                ('allOkShipping', models.BooleanField(blank='true', default=None, null=True)),
                ('comentarioShipping', models.CharField(max_length=350, null=True)),
            ],
            options={
                'verbose_name': 'Warehouse - Production - History All Time',
                'verbose_name_plural': 'Warehouse - Production - History All Time',
            },
        ),
        migrations.CreateModel(
            name='Prodlines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Prodlines',
                'verbose_name_plural': 'Prodlines',
            },
        ),
        migrations.CreateModel(
            name='ProdlineTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50, null=True)),
                ('line', models.CharField(max_length=50, null=True)),
                ('site', models.CharField(max_length=50, null=True)),
                ('due_date', models.CharField(max_length=50, null=True)),
                ('item_number', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=50, null=True)),
                ('to_complete', models.CharField(max_length=50, null=True)),
                ('receiving', models.BooleanField(blank='true', default=None, null=True)),
                ('comentarioReceiving', models.CharField(max_length=350, null=True)),
                ('shipping', models.BooleanField(blank='true', default=None, null=True)),
                ('comentarioShipping', models.CharField(max_length=350, null=True)),
                ('allOkReceiving', models.BooleanField(blank='true', default=None, null=True)),
                ('allOkShipping', models.BooleanField(blank='true', default=None, null=True)),
            ],
            options={
                'verbose_name': 'Warehouse - Production',
                'verbose_name_plural': 'Warehouse - Production',
            },
        ),
        migrations.CreateModel(
            name='ProdlineTableHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50, null=True)),
                ('line', models.CharField(max_length=50, null=True)),
                ('site', models.CharField(max_length=50, null=True)),
                ('due_date', models.CharField(max_length=50, null=True)),
                ('item_number', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=50, null=True)),
                ('to_complete', models.CharField(max_length=50, null=True)),
                ('receiving', models.BooleanField(blank='true', default=None, null=True)),
                ('allOkReceiving', models.BooleanField(blank='true', default=None, null=True)),
                ('comentarioReceiving', models.CharField(max_length=350, null=True)),
                ('shipping', models.BooleanField(blank='true', default=None, null=True)),
                ('allOkShipping', models.BooleanField(blank='true', default=None, null=True)),
                ('comentarioShipping', models.CharField(max_length=350, null=True)),
            ],
            options={
                'verbose_name': 'Warehouse - Production - History',
                'verbose_name_plural': 'Warehouse - Production - History',
            },
        ),
    ]
