# Generated by Django 3.0.7 on 2022-03-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoCafetaria2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=50, null=True)),
                ('seguro', models.CharField(max_length=50, null=True)),
                ('comentarios', models.CharField(max_length=3500, null=True)),
            ],
            options={
                'verbose_name': 'Historico Cafetaria',
                'verbose_name_plural': 'Historico Cafetaria',
            },
        ),
        migrations.CreateModel(
            name='HistoricoPortaria2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=50, null=True)),
                ('seguro', models.CharField(max_length=50, null=True)),
                ('comentarios', models.CharField(max_length=3500, null=True)),
            ],
            options={
                'verbose_name': 'Historico Portaria',
                'verbose_name_plural': 'Historico Portaria',
            },
        ),
        migrations.CreateModel(
            name='LinguagemCafetaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Linguagem Cafetaria',
                'verbose_name_plural': 'Linguagem Cafetaria',
            },
        ),
        migrations.CreateModel(
            name='LinguagemPortaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Linguagem Portaria',
                'verbose_name_plural': 'Linguagem Portaria',
            },
        ),
    ]
