# Generated by Django 2.1.15 on 2022-01-04 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buttonAuthorHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50, null=True)),
                ('autor', models.CharField(max_length=50, null=True)),
                ('horaAlteracao', models.CharField(max_length=50, null=True)),
                ('horaPedido', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Request History Authors',
                'verbose_name_plural': 'Request History Authors',
            },
        ),
        migrations.CreateModel(
            name='extraProductHistoric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=50, null=True)),
                ('produto', models.CharField(max_length=50, null=True)),
                ('embalagem', models.CharField(max_length=50, null=True)),
                ('quantidade', models.CharField(max_length=50, null=True)),
                ('startTime', models.CharField(max_length=50, null=True)),
                ('dataPedido', models.CharField(max_length=50, null=True)),
                ('dataTerminado', models.CharField(max_length=50, null=True)),
                ('comentario', models.CharField(max_length=250, null=True)),
                ('estado', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Historic Table',
                'verbose_name_plural': 'Historic Table',
            },
        ),
        migrations.CreateModel(
            name='extraProductTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=50, null=True)),
                ('produto', models.CharField(max_length=50, null=True)),
                ('embalagem', models.CharField(max_length=50, null=True)),
                ('quantidade', models.CharField(max_length=50, null=True)),
                ('startTime', models.CharField(max_length=50, null=True)),
                ('dataPedido', models.CharField(max_length=50, null=True)),
                ('dataTerminado', models.CharField(max_length=50, null=True)),
                ('link', models.CharField(max_length=50, null=True)),
                ('estado', models.CharField(max_length=50, null=True)),
                ('autor', models.CharField(max_length=50, null=True)),
                ('tempoSupply', models.IntegerField(blank='true', default=0, null=True)),
                ('tempoSupplyRestante', models.IntegerField(blank='true', default=0, null=True)),
                ('tempoLimite', models.CharField(max_length=50, null=True)),
                ('ultimosDez', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Request Table',
                'verbose_name_plural': 'Request Table',
            },
        ),
        migrations.CreateModel(
            name='PartNumbersExpendable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pn', models.CharField(max_length=50, null=True)),
                ('descricao', models.CharField(max_length=150, null=True)),
                ('link', models.CharField(max_length=50, null=True)),
                ('quantidade', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Part Numbers Expendable',
                'verbose_name_plural': 'Part Numbers Expendable',
            },
        ),
        migrations.CreateModel(
            name='PartNumbersReturnable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pn', models.CharField(max_length=50, null=True)),
                ('descricao', models.CharField(max_length=150, null=True)),
                ('link', models.CharField(max_length=50, null=True)),
                ('quantidade', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Part Numbers Returnable',
                'verbose_name_plural': 'Part Numbers Returnable',
            },
        ),
        migrations.AddField(
            model_name='buttonauthorhistory',
            name='embalagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pManagement.extraProductTable'),
        ),
    ]
