# Generated by Django 3.0.7 on 2022-04-26 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pManagement', '0002_stockelements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockelements',
            name='fixo',
        ),
    ]
